[custom]
;0、DNS设置
clash_rule_base=https://raw.githubusercontent.com/Blaine-Li/SomeDomain/refs/heads/master/test.yml

;1、域名组
ruleset=➡️ 国内,https://raw.githubusercontent.com/Blaine-Li/SomeDomain/master/Mydomain.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=👽 AI,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI.list
ruleset=👽 AI,https://raw.githubusercontent.com/Blaine-Li/SomeDomain/refs/heads/master/AI2.list
ruleset=👽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=👽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list
ruleset=👽 AI,https://gist.githubusercontent.com/Blaine-Li/d954c04c3d6c763774915fbbfe1e94c2/raw/fb0ec120474451b276ce8f7a8d11042f61df59fa/Facebook.list
;ruleset=👽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=👽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PayPal/PayPal.list
ruleset=👽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Binance/Binance.list
ruleset=👽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OKX/OKX.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/YouTube.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list
ruleset=🌍 国外,https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=➡️ 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=➡️ 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=➡️ 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=➡️ 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=➡️ 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=➡️ 国内,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🐟 漏网之鱼,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=👽 AI`select`[]台湾-自动`[]香港-自动`[]新加坡-自动`[]日本-自动`[]美国-自动`[]所有-选择`[]DIRECT
custom_proxy_group=🌍 国外`select`[]香港-自动`[]台湾-自动`[]新加坡-自动`[]日本-自动`[]美国-自动`[]所有-选择`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]香港-自动`[]台湾-自动`[]新加坡-自动`[]日本-自动`[]美国-自动`[]所有-选择`[]DIRECT
custom_proxy_group=➡️ 国内`select`[]DIRECT

;3、节点组
custom_proxy_group=香港-自动`url-test`(香港|Hong Kong|HongKong)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=台湾-自动`url-test`(台湾|Taiwan)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=新加坡-自动`url-test`(新加坡|Singapore)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=日本-自动`url-test`(日本|Japan)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=美国-自动`url-test`(美国|USA|🇺🇸)`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=所有-选择`select`.*`

;4、启用规则集
enable_rule_generator=true
overwrite_original_rules=true
